# MySQL in Jupyter

This is an example notebook to illustrate how to use MySQL from within a Jupyter notenook.  
We will walk through connecting to a MySQL server, how to make form simple SQL queries,  
how to capture large result sets, and how to download the results in CSV format (to make  
it easy to get subsets of a database into an Excel spreadsheet in your PC.

> "Everything should be made as simple as possible, but not simpler."  
 \- Albert Einstein

***

## MySQL example tutorial

In this example you will learn how to connect to the database server,  
see which databases are installed, discover the structure of tables in a database.

Once we understand the database structure, we can run queries against the tables in  
the database, and then save the results for further analysis.

***

### step 1: load the sql library

Before we do anything else, we must first tell Jupyter to load a sql 'magic' module.  
The sql module enables us to make database connections and query the database.

The command to load the sql 'magic' is
```python
load_ext sql
```

In [1]:
load_ext sql

***

### step 2: connect to the database

After the sql module is loaded, we tell it to log into a MySQL database.

The command 
```mySQL
mysql://tester:badpassword@mysqlserver/employees
```
logs us into the mysql server at the server 'mysqlserver' as the user 'tester' and selects
the database named 'employees'

In [2]:
%sql mysql://tester:badpassword@mysqlserver/employees

'Connected: tester@employees'

***
### step 3: SQL commands to find databases and tables

Let's see what databases are available on this server.

The command
```mySQL
show databases
```
will list all the databases available to us. MySQL usues some database  
internally to keep track of settings and other housekeeping tasks, so  
here we will see a housekeeping databases (information_schema). 

For this course, we are only interested in the database named 'employees'.

In [3]:
%sql show databases;

4 rows affected.

[('information_schema',), ('employees',), ('mysql',), ('performance_schema',)]

The information_schema database is where mysql does some bookkeeping on  
the structure of other databases. The 'employees' database contains the  
tables we want to look at since it has employee, department, and salary data.

If we don't already know the structure of the employees database, we can  
ask MySQL to tell us about the tables that make up the database with the command
```mySQL
show tables;
```

In [4]:
%sql show tables;

6 rows affected.

[('departments',),
 ('dept_emp',),
 ('dept_manager',),
 ('employees',),
 ('salaries',),
 ('titles',)]

You can see that there are 6 tables in this database. 
***

## step 4: Discover the table structure

How do can we discover the table structures for each of these tables? 

If we know the names of a table, we can ask mySQL to describe it.  
For example, we can ask for a description of the departments table with the command
```mySQL
describe departments;
```

In [5]:
%sql describe departments;

2 rows affected.

[('dept_no', 'char(4)', 'NO', 'PRI', None, ''),
 ('dept_name', 'varchar(40)', 'NO', 'UNI', None, '')]

***
## step 5: How big is the table?

Its a good idea to have a rough sense of how big a table is before  
you start running queries so you don't accidentally request a couple  
million rows of results. 

To do this we want a query that will count all the rows. The command to do this is
```mySQL
select count(*) from departments;
```
Let's see how big the departments table is:

In [6]:
%sql select count(*) from departments;

1 rows affected.

[(9,)]

The departments table is not very big, so it should be reasonably safe  
to query for everything in the table. 

The command
```mySQL
select * from departments;
```
will match every column in every row in the table. 

For this table we get 9 rows of results:

In [7]:
%sql select * from departments;

9 rows affected.

[('d009', 'Customer Service'),
 ('d005', 'Development'),
 ('d002', 'Finance'),
 ('d003', 'Human Resources'),
 ('d001', 'Marketing'),
 ('d004', 'Production'),
 ('d006', 'Quality Management'),
 ('d008', 'Research'),
 ('d007', 'Sales')]

***

## step 6: Selecting a subset of a table

The employees table is much larger (and more complex) than the departments table.

Let's use commands we already know to discover the table structure and size:

In [8]:
%sql describe employees

6 rows affected.

[('emp_no', 'int(11)', 'NO', 'PRI', None, ''),
 ('birth_date', 'date', 'NO', '', None, ''),
 ('first_name', 'varchar(14)', 'NO', '', None, ''),
 ('last_name', 'varchar(16)', 'NO', '', None, ''),
 ('gender', "enum('M','F')", 'NO', '', None, ''),
 ('hire_date', 'date', 'NO', '', None, '')]

In [9]:
%sql select count(*) from employees

1 rows affected.

[(300024,)]

We probably don't want to select all 300,024 rows in the employees table,  
so we are going to need a better selet statement. 

Select statements can include an optional 'where' clause to limit the scope  
of the select. By limiting scope we can cut down on the number of rows returned.

Since we know the names of the columns in the table, we could limit the select  
scope to the rows that have a specific value for one of the columns. 

For example, if I wanted to count all the of employees with the first name 'Mark' 
I could add the clause
```mySQL
where first_name = 'Mark'
```
to the select statement I previously used to count the rows in the table. 

So, to count all the employees named Mark, my select satatement would be
```mySQL
select count(*) from employees where first_name = 'Mark'
```

In [10]:
%sql select count(*) from employees where first_name = 'Mark'

1 rows affected.

[(230,)]

230 rows of results looks like a managable number, so let's get the detailed results with this query
```SQL
select * from employees where first_name = 'Mark'
```

In [11]:
%sql select * from employees where first_name = 'Mark'

230 rows affected.

[(10415, datetime.date(1957, 11, 12), 'Mark', 'Coorg', 'M', datetime.date(1993, 10, 25)),
 (13517, datetime.date(1961, 2, 22), 'Mark', 'Setlzner', 'M', datetime.date(1988, 1, 2)),
 (14248, datetime.date(1955, 10, 13), 'Mark', 'Alblas', 'M', datetime.date(1989, 5, 24)),
 (14335, datetime.date(1955, 9, 16), 'Mark', 'Fraisse', 'M', datetime.date(1997, 10, 9)),
 (15031, datetime.date(1956, 12, 22), 'Mark', 'Naumovich', 'M', datetime.date(1992, 9, 7)),
 (17371, datetime.date(1958, 2, 3), 'Mark', 'Sankaranarayanan', 'F', datetime.date(1988, 10, 16)),
 (17551, datetime.date(1954, 2, 21), 'Mark', 'Foote', 'F', datetime.date(1998, 10, 4)),
 (19561, datetime.date(1957, 2, 23), 'Mark', 'Kinley', 'F', datetime.date(1987, 4, 30)),
 (20189, datetime.date(1955, 2, 19), 'Mark', 'Nanard', 'M', datetime.date(1986, 8, 28)),
 (20945, datetime.date(1955, 12, 22), 'Mark', 'Marsiglia', 'F', datetime.date(1998, 7, 3)),
 (22481, datetime.date(1953, 7, 13), 'Mark', 'Ciolek', 'F', datetime.date(1991, 4, 9)),
 (23195, datetime.date(1952, 5, 27), 'Mark', 'Ertl', 'M', datetime.date(1986, 9, 25)),
 (24632, datetime.date(1958, 11, 3), 'Mark', 'Harllee', 'M', datetime.date(1989, 9, 22)),
 (27746, datetime.date(1964, 11, 29), 'Mark', 'Lunn', 'M', datetime.date(1987, 9, 22)),
 (31568, datetime.date(1965, 1, 10), 'Mark', 'Lalonde', 'M', datetime.date(1985, 12, 24)),
 (33764, datetime.date(1956, 10, 9), 'Mark', 'Deville', 'M', datetime.date(1985, 4, 29)),
 (37408, datetime.date(1955, 10, 28), 'Mark', 'Boguraev', 'M', datetime.date(1990, 9, 16)),
 (38410, datetime.date(1958, 6, 19), 'Mark', 'Melichar', 'M', datetime.date(1992, 2, 17)),
 (39969, datetime.date(1955, 10, 15), 'Mark', 'Conia', 'M', datetime.date(1985, 12, 9)),
 (42974, datetime.date(1962, 7, 27), 'Mark', 'Brookman', 'M', datetime.date(1989, 12, 6)),
 (43153, datetime.date(1963, 8, 27), 'Mark', 'McConalogue', 'F', datetime.date(1997, 8, 11)),
 (44900, datetime.date(1965, 1, 5), 'Mark', 'Schwaller', 'F', datetime.date(1989, 9, 6)),
 (46720, datetime.date(1964, 7, 4), 'Mark', 'Sethi', 'M', datetime.date(1986, 3, 27)),
 (47842, datetime.date(1960, 8, 16), 'Mark', 'Sigstam', 'M', datetime.date(1989, 5, 21)),
 (50359, datetime.date(1963, 9, 23), 'Mark', 'Feldmann', 'M', datetime.date(1987, 3, 25)),
 (50872, datetime.date(1955, 1, 12), 'Mark', 'Hanabata', 'F', datetime.date(1993, 10, 31)),
 (51175, datetime.date(1953, 8, 18), 'Mark', 'Lorho', 'M', datetime.date(1987, 4, 13)),
 (52014, datetime.date(1962, 7, 5), 'Mark', 'Peres', 'M', datetime.date(1994, 9, 23)),
 (54842, datetime.date(1961, 2, 23), 'Mark', 'Nitto', 'M', datetime.date(1994, 12, 21)),
 (56628, datetime.date(1955, 10, 21), 'Mark', 'Esposito', 'F', datetime.date(1986, 6, 28)),
 (56767, datetime.date(1952, 6, 27), 'Mark', 'Trelles', 'M', datetime.date(1988, 5, 6)),
 (57141, datetime.date(1960, 3, 28), 'Mark', 'Oxenboll', 'M', datetime.date(1986, 1, 28)),
 (57724, datetime.date(1955, 10, 24), 'Mark', 'Cools', 'F', datetime.date(1994, 2, 20)),
 (58209, datetime.date(1957, 11, 17), 'Mark', 'Ermel', 'M', datetime.date(1989, 2, 19)),
 (58367, datetime.date(1964, 9, 15), 'Mark', 'Goldhammer', 'F', datetime.date(1993, 9, 29)),
 (59357, datetime.date(1964, 7, 6), 'Mark', 'Barriga', 'M', datetime.date(1986, 12, 5)),
 (61274, datetime.date(1955, 1, 6), 'Mark', 'Antonisse', 'M', datetime.date(1997, 3, 18)),
 (62284, datetime.date(1961, 10, 10), 'Mark', 'Hebden', 'M', datetime.date(1987, 2, 5)),
 (63343, datetime.date(1953, 4, 22), 'Mark', 'Ananiadou', 'M', datetime.date(1988, 9, 28)),
 (63478, datetime.date(1957, 11, 4), 'Mark', 'Godskesen', 'F', datetime.date(1986, 3, 26)),
 (64178, datetime.date(1959, 3, 14), 'Mark', 'Conde', 'F', datetime.date(1986, 1, 11)),
 (64961, datetime.date(1960, 8, 23), 'Mark', 'Jording', 'M', datetime.date(1986, 6, 29)),
 (65161, datetime.date(1957, 1, 3), 'Mark', 'Dymetman', 'F', datetime.date(1987, 7, 24)),
 (65568, datetime.date(1952, 8, 9), 'Mark', 'Ventosa', 'M', datetime.date(1988, 11, 26)),
 (67026, datetime.date(1960, 6, 23), 'Mark', 'Lenart', 'M', datetime.date(1992, 11, 9)),
 (67655, datetime.date(1955, 9, 30), 'Mark', 'Dichev', 'M', datetime.date(1993, 3, 8)),
 (73041, datetime.date(1956, 7, 28), 'Mark', 'Hiroyama', 'F', datetime.date(1985, 9, 13)),
 (73453, datetime.date(1964, 1, 8), 'Mark', 'Boyle', 'M', datetime.date(1986, 5, 12)),
 (73725, datetime.date(1961, 10, 25), 'Mark', 'Giveon', 'F', datetime.date(1989, 4, 2)),
 (73761, datetime.date(1954, 6, 3), 'Mark', 'Birge', 'F', datetime.date(1988, 1, 13)),
 (74878, datetime.date(1955, 8, 2), 'Mark', 'Leaver', 'F', datetime.date(1988, 9, 15)),
 (75663, datetime.date(1964, 5, 27), 'Mark', 'Baez', 'M', datetime.date(1991, 1, 24)),
 (76139, datetime.date(1954, 7, 23), 'Mark', 'Speer', 'F', datetime.date(1988, 7, 30)),
 (77905, datetime.date(1962, 8, 4), 'Mark', 'Msuda', 'M', datetime.date(1994, 7, 10)),
 (83630, datetime.date(1954, 4, 22), 'Mark', 'Magalhaes', 'F', datetime.date(1994, 9, 13)),
 (83768, datetime.date(1954, 7, 11), 'Mark', 'Ariola', 'M', datetime.date(1986, 3, 5)),
 (84846, datetime.date(1962, 10, 23), 'Mark', 'Papadias', 'M', datetime.date(1989, 9, 22)),
 (84889, datetime.date(1958, 8, 9), 'Mark', 'Thimonier', 'M', datetime.date(1997, 11, 6)),
 (85732, datetime.date(1961, 9, 15), 'Mark', 'Rodier', 'F', datetime.date(1989, 4, 13)),
 (86172, datetime.date(1963, 3, 16), 'Mark', 'Ernst', 'F', datetime.date(1990, 4, 13)),
 (90325, datetime.date(1952, 3, 28), 'Mark', 'Krone', 'M', datetime.date(1989, 6, 27)),
 (90591, datetime.date(1955, 7, 31), 'Mark', 'Vesna', 'M', datetime.date(1987, 12, 11)),
 (91513, datetime.date(1958, 6, 13), 'Mark', 'Bellmore', 'M', datetime.date(1994, 7, 22)),
 (93697, datetime.date(1960, 4, 5), 'Mark', 'Feinberg', 'M', datetime.date(1991, 8, 18)),
 (94547, datetime.date(1957, 2, 24), 'Mark', 'Mitchem', 'F', datetime.date(1985, 8, 12)),
 (96365, datetime.date(1958, 12, 23), 'Mark', 'Rossi', 'M', datetime.date(1992, 8, 6)),
 (98507, datetime.date(1961, 9, 28), 'Mark', 'Nergos', 'M', datetime.date(1987, 8, 31)),
 (100774, datetime.date(1958, 11, 22), 'Mark', 'Kroha', 'M', datetime.date(1991, 4, 18)),
 (100846, datetime.date(1955, 8, 30), 'Mark', 'Kalloufi', 'F', datetime.date(1986, 1, 30)),
 (100972, datetime.date(1964, 4, 24), 'Mark', 'Validov', 'F', datetime.date(1985, 9, 21)),
 (102150, datetime.date(1960, 10, 26), 'Mark', 'Luiz', 'F', datetime.date(1989, 2, 15)),
 (102401, datetime.date(1953, 8, 31), 'Mark', 'Rathonyi', 'M', datetime.date(1993, 9, 14)),
 (106091, datetime.date(1954, 11, 10), 'Mark', 'Nittel', 'F', datetime.date(1985, 7, 2)),
 (106902, datetime.date(1955, 8, 30), 'Mark', 'Pillow', 'M', datetime.date(1993, 2, 1)),
 (107124, datetime.date(1963, 2, 23), 'Mark', 'Piazza', 'M', datetime.date(1985, 12, 3)),
 (109698, datetime.date(1961, 6, 3), 'Mark', 'Akazan', 'F', datetime.date(1990, 6, 10)),
 (203167, datetime.date(1964, 5, 25), 'Mark', 'Basawa', 'M', datetime.date(1997, 11, 20)),
 (205721, datetime.date(1958, 3, 9), 'Mark', 'Swen', 'F', datetime.date(1988, 9, 13)),
 (206910, datetime.date(1962, 6, 8), 'Mark', 'Kroha', 'F', datetime.date(1993, 10, 23)),
 (208022, datetime.date(1964, 6, 16), 'Mark', 'Perng', 'M', datetime.date(1991, 5, 11)),
 (208341, datetime.date(1960, 3, 24), 'Mark', 'Solares', 'M', datetime.date(1995, 11, 10)),
 (208943, datetime.date(1952, 10, 30), 'Mark', 'Roccetti', 'F', datetime.date(1992, 9, 21)),
 (208976, datetime.date(1960, 2, 24), 'Mark', 'Reeken', 'M', datetime.date(1995, 9, 21)),
 (209537, datetime.date(1964, 1, 27), 'Mark', 'Linnainmaa', 'F', datetime.date(1990, 6, 24)),
 (210067, datetime.date(1952, 9, 2), 'Mark', 'Bresenham', 'M', datetime.date(1988, 11, 10)),
 (210487, datetime.date(1958, 10, 13), 'Mark', 'Neimat', 'F', datetime.date(1989, 6, 24)),
 (212107, datetime.date(1963, 11, 18), 'Mark', 'Heystek', 'M', datetime.date(1986, 8, 12)),
 (214027, datetime.date(1962, 10, 10), 'Mark', 'Raney', 'F', datetime.date(1989, 1, 4)),
 (215101, datetime.date(1952, 10, 23), 'Mark', 'Baaz', 'F', datetime.date(1987, 8, 8)),
 (215264, datetime.date(1963, 8, 4), 'Mark', 'Docker', 'M', datetime.date(1991, 4, 12)),
 (218388, datetime.date(1957, 8, 16), 'Mark', 'Schicker', 'M', datetime.date(1985, 12, 1)),
 (220042, datetime.date(1955, 1, 16), 'Mark', 'Frijda', 'F', datetime.date(1994, 1, 25)),
 (220064, datetime.date(1954, 5, 14), 'Mark', 'Ramras', 'F', datetime.date(1987, 1, 17)),
 (221017, datetime.date(1957, 7, 3), 'Mark', 'Levergood', 'F', datetime.date(1988, 8, 29)),
 (222301, datetime.date(1962, 3, 17), 'Mark', 'Sinitsyn', 'F', datetime.date(1995, 1, 1)),
 (224051, datetime.date(1953, 8, 5), 'Mark', 'Syrzycki', 'F', datetime.date(1985, 10, 12)),
 (227456, datetime.date(1952, 10, 27), 'Mark', 'Bach', 'F', datetime.date(1986, 5, 26)),
 (227685, datetime.date(1956, 1, 5), 'Mark', 'Ellozy', 'M', datetime.date(1985, 5, 18)),
 (227716, datetime.date(1959, 10, 1), 'Mark', 'Pocchiola', 'M', datetime.date(1992, 6, 28)),
 (228512, datetime.date(1960, 3, 31), 'Mark', 'Sridhar', 'M', datetime.date(1997, 5, 31)),
 (229010, datetime.date(1961, 11, 12), 'Mark', 'Cappelli', 'M', datetime.date(1990, 5, 7)),
 (229616, datetime.date(1959, 11, 11), 'Mark', 'Naudin', 'M', datetime.date(1992, 9, 15)),
 (234996, datetime.date(1954, 9, 3), 'Mark', 'Hasham', 'M', datetime.date(1988, 5, 7)),
 (237396, datetime.date(1963, 12, 8), 'Mark', 'Krider', 'F', datetime.date(1988, 10, 8)),
 (238530, datetime.date(1961, 9, 3), 'Mark', 'Zirintsis', 'M', datetime.date(1988, 7, 16)),
 (239869, datetime.date(1960, 9, 15), 'Mark', 'Savasere', 'F', datetime.date(1992, 11, 4)),
 (241444, datetime.date(1957, 12, 4), 'Mark', 'Jenevein', 'M', datetime.date(1985, 6, 12)),
 (245003, datetime.date(1959, 9, 29), 'Mark', 'Veldwijk', 'M', datetime.date(1992, 2, 25)),
 (245069, datetime.date(1953, 3, 3), 'Mark', 'Bennis', 'M', datetime.date(1990, 4, 25)),
 (245887, datetime.date(1958, 2, 18), 'Mark', 'Armand', 'F', datetime.date(1989, 9, 21)),
 (248926, datetime.date(1963, 3, 2), 'Mark', 'Ozery', 'M', datetime.date(1987, 5, 17)),
 (250889, datetime.date(1959, 5, 1), 'Mark', 'Rathonyi', 'F', datetime.date(1994, 11, 11)),
 (252711, datetime.date(1963, 2, 14), 'Mark', 'Liedekerke', 'M', datetime.date(1985, 4, 21)),
 (254690, datetime.date(1960, 6, 25), 'Mark', 'Garigliano', 'F', datetime.date(1996, 12, 18)),
 (255897, datetime.date(1954, 7, 2), 'Mark', 'Khalid', 'M', datetime.date(1992, 12, 1)),
 (256036, datetime.date(1963, 3, 26), 'Mark', 'Spelt', 'M', datetime.date(1988, 9, 24)),
 (258024, datetime.date(1964, 5, 28), 'Mark', 'Strooper', 'M', datetime.date(1986, 1, 26)),
 (259979, datetime.date(1957, 1, 4), 'Mark', 'Rosiles', 'M', datetime.date(1986, 9, 30)),
 (261737, datetime.date(1965, 1, 23), 'Mark', 'Lindqvist', 'M', datetime.date(1987, 3, 18)),
 (264685, datetime.date(1958, 5, 11), 'Mark', 'Peroz', 'M', datetime.date(1987, 5, 30)),
 (266961, datetime.date(1957, 12, 3), 'Mark', 'Geffroy', 'F', datetime.date(1985, 5, 27)),
 (268577, datetime.date(1962, 2, 19), 'Mark', 'Mansanne', 'F', datetime.date(1987, 3, 24)),
 (269632, datetime.date(1956, 1, 3), 'Mark', 'Fontet', 'F', datetime.date(1991, 8, 19)),
 (270550, datetime.date(1960, 3, 3), 'Mark', 'Porenta', 'M', datetime.date(1986, 4, 12)),
 (271014, datetime.date(1958, 3, 8), 'Mark', 'Molenkamp', 'F', datetime.date(1992, 11, 30)),
 (271207, datetime.date(1963, 9, 30), 'Mark', 'Jonsson', 'M', datetime.date(1986, 8, 1)),
 (272577, datetime.date(1952, 3, 18), 'Mark', 'Glinert', 'M', datetime.date(1985, 4, 27)),
 (273163, datetime.date(1963, 12, 5), 'Mark', 'Garnham', 'M', datetime.date(1987, 8, 20)),
 (273462, datetime.date(1957, 5, 26), 'Mark', 'Luga', 'M', datetime.date(1993, 8, 18)),
 (275791, datetime.date(1964, 8, 16), 'Mark', 'Narahari', 'M', datetime.date(1986, 8, 17)),
 (275826, datetime.date(1961, 12, 19), 'Mark', 'Bharadwaj', 'M', datetime.date(1989, 5, 16)),
 (277272, datetime.date(1956, 12, 5), 'Mark', 'Mandell', 'M', datetime.date(1991, 8, 20)),
 (283070, datetime.date(1954, 9, 15), 'Mark', 'Radivojevic', 'M', datetime.date(1988, 6, 28)),
 (283135, datetime.date(1956, 9, 29), 'Mark', 'Clemencon', 'M', datetime.date(1987, 12, 25)),
 (285353, datetime.date(1952, 12, 28), 'Mark', 'Radivojevic', 'F', datetime.date(1990, 1, 28)),
 (287675, datetime.date(1952, 5, 30), 'Mark', 'Baak', 'F', datetime.date(1988, 2, 2)),
 (289229, datetime.date(1958, 3, 4), 'Mark', 'Chorvat', 'M', datetime.date(1987, 7, 9)),
 (289616, datetime.date(1955, 8, 8), 'Mark', 'Fasbender', 'M', datetime.date(1986, 6, 27)),
 (291052, datetime.date(1952, 11, 30), 'Mark', 'Gargeya', 'F', datetime.date(1988, 4, 27)),
 (291141, datetime.date(1964, 11, 6), 'Mark', 'Benveniste', 'F', datetime.date(1985, 3, 5)),
 (291463, datetime.date(1961, 7, 11), 'Mark', 'McClure', 'F', datetime.date(1989, 6, 3)),
 (291521, datetime.date(1964, 6, 8), 'Mark', 'Zhiwei', 'F', datetime.date(1988, 6, 20)),
 (294353, datetime.date(1952, 11, 27), 'Mark', 'Vanwelkenhuysen', 'F', datetime.date(1986, 6, 22)),
 (294640, datetime.date(1964, 6, 10), 'Mark', 'Ranta', 'M', datetime.date(1989, 1, 27)),
 (295549, datetime.date(1960, 2, 1), 'Mark', 'Holburn', 'M', datetime.date(1995, 9, 27)),
 (296985, datetime.date(1956, 3, 2), 'Mark', 'Miculan', 'F', datetime.date(1986, 4, 8)),
 (297205, datetime.date(1963, 9, 24), 'Mark', 'Birrer', 'F', datetime.date(1985, 4, 4)),
 (297914, datetime.date(1952, 11, 26), 'Mark', 'Brandsma', 'M', datetime.date(1987, 1, 14)),
 (298525, datetime.date(1958, 7, 10), 'Mark', 'Klassen', 'M', datetime.date(1986, 5, 6)),
 (299203, datetime.date(1961, 12, 11), 'Mark', 'Itzigehl', 'M', datetime.date(1990, 5, 25)),
 (299552, datetime.date(1955, 8, 23), 'Mark', 'Onuegbe', 'F', datetime.date(1995, 12, 1)),
 (299590, datetime.date(1961, 8, 28), 'Mark', 'Setia', 'M', datetime.date(1994, 8, 2)),
 (400266, datetime.date(1953, 1, 30), 'Mark', 'Stellhorn', 'F', datetime.date(1986, 4, 30)),
 (400565, datetime.date(1954, 4, 4), 'Mark', 'Rusterholz', 'M', datetime.date(1988, 1, 5)),
 (400769, datetime.date(1961, 6, 1), 'Mark', 'Radivojevic', 'M', datetime.date(1990, 7, 1)),
 (400795, datetime.date(1958, 2, 11), 'Mark', 'Socorro', 'M', datetime.date(1989, 6, 15)),
 (400873, datetime.date(1955, 6, 10), 'Mark', 'Butner', 'M', datetime.date(1988, 2, 14)),
 (402416, datetime.date(1964, 9, 6), 'Mark', 'Sudbeck', 'M', datetime.date(1991, 6, 19)),
 (403195, datetime.date(1959, 4, 5), 'Mark', 'Chorvat', 'M', datetime.date(1997, 2, 4)),
 (406123, datetime.date(1956, 5, 22), 'Mark', 'Birjandi', 'M', datetime.date(1986, 8, 20)),
 (407699, datetime.date(1958, 2, 3), 'Mark', 'Godskesen', 'M', datetime.date(1985, 4, 12)),
 (409333, datetime.date(1962, 1, 16), 'Mark', 'Griswold', 'M', datetime.date(1994, 2, 22)),
 (411576, datetime.date(1953, 8, 7), 'Mark', 'Bonifati', 'F', datetime.date(1991, 4, 7)),
 (413524, datetime.date(1955, 10, 4), 'Mark', 'Marsiglia', 'F', datetime.date(1991, 7, 26)),
 (415042, datetime.date(1957, 11, 7), 'Mark', 'Erdmenger', 'M', datetime.date(1985, 10, 16)),
 (416242, datetime.date(1956, 10, 3), 'Mark', 'Jayawardene', 'M', datetime.date(1994, 11, 25)),
 (418536, datetime.date(1954, 2, 27), 'Mark', 'Weiland', 'M', datetime.date(1986, 9, 21)),
 (420283, datetime.date(1958, 8, 30), 'Mark', 'Bierbaum', 'F', datetime.date(1993, 8, 27)),
 (421361, datetime.date(1963, 9, 26), 'Mark', 'Birrer', 'M', datetime.date(1988, 8, 1)),
 (421999, datetime.date(1955, 7, 20), 'Mark', 'Perng', 'M', datetime.date(1986, 3, 7)),
 (422051, datetime.date(1956, 7, 17), 'Mark', 'Baaz', 'F', datetime.date(1988, 10, 20)),
 (424253, datetime.date(1956, 10, 27), 'Mark', 'Jarecki', 'F', datetime.date(1989, 9, 22)),
 (425446, datetime.date(1959, 7, 2), 'Mark', 'Heinisuo', 'M', datetime.date(1986, 10, 15)),
 (427033, datetime.date(1960, 2, 27), 'Mark', 'Przulj', 'M', datetime.date(1991, 6, 6)),
 (427269, datetime.date(1953, 8, 28), 'Mark', 'Ginesta', 'M', datetime.date(1985, 12, 18)),
 (427392, datetime.date(1952, 6, 22), 'Mark', 'Schwartzburd', 'M', datetime.date(1992, 6, 29)),
 (427718, datetime.date(1963, 3, 29), 'Mark', 'Heijenga', 'F', datetime.date(1985, 12, 12)),
 (430368, datetime.date(1959, 4, 4), 'Mark', 'Pelz', 'M', datetime.date(1986, 3, 9)),
 (430396, datetime.date(1952, 3, 21), 'Mark', 'Furedi', 'F', datetime.date(1992, 11, 21)),
 (431949, datetime.date(1961, 10, 14), 'Mark', 'Gulla', 'F', datetime.date(1990, 12, 4)),
 (434321, datetime.date(1958, 12, 27), 'Mark', 'Schieder', 'F', datetime.date(1985, 9, 8)),
 (435770, datetime.date(1959, 1, 9), 'Mark', 'Wielonsky', 'M', datetime.date(1993, 5, 13)),
 (436144, datetime.date(1953, 11, 18), 'Mark', 'Morrow', 'F', datetime.date(1985, 7, 20)),
 (440538, datetime.date(1954, 3, 24), 'Mark', 'Kroha', 'F', datetime.date(1996, 1, 6)),
 (442131, datetime.date(1953, 5, 24), 'Mark', 'Dredge', 'M', datetime.date(1986, 6, 25)),
 (442482, datetime.date(1952, 10, 26), 'Mark', 'Mundy', 'F', datetime.date(1997, 6, 3)),
 (442765, datetime.date(1955, 9, 25), 'Mark', 'Yeung', 'F', datetime.date(1985, 4, 13)),
 (444144, datetime.date(1953, 8, 28), 'Mark', 'Denny', 'M', datetime.date(1991, 10, 2)),
 (444304, datetime.date(1957, 3, 24), 'Mark', 'Awdeh', 'M', datetime.date(1992, 10, 17)),
 (445938, datetime.date(1961, 2, 25), 'Mark', 'Rosin', 'F', datetime.date(1987, 2, 10)),
 (448227, datetime.date(1957, 6, 21), 'Mark', 'Rosar', 'F', datetime.date(1988, 1, 4)),
 (453725, datetime.date(1952, 9, 4), 'Mark', 'Zweizig', 'F', datetime.date(1994, 11, 24)),
 (455151, datetime.date(1963, 12, 20), 'Mark', 'Narahara', 'M', datetime.date(1987, 9, 25)),
 (457645, datetime.date(1962, 8, 30), 'Mark', 'Stassinopoulos', 'M', datetime.date(1986, 4, 30)),
 (459671, datetime.date(1954, 1, 30), 'Mark', 'Flowers', 'F', datetime.date(1988, 2, 8)),
 (460194, datetime.date(1957, 12, 14), 'Mark', 'Hennings', 'M', datetime.date(1985, 8, 28)),
 (461415, datetime.date(1964, 7, 22), 'Mark', 'Welham', 'M', datetime.date(1994, 11, 25)),
 (461455, datetime.date(1964, 8, 6), 'Mark', 'McConalogue', 'F', datetime.date(1998, 2, 25)),
 (462499, datetime.date(1959, 12, 18), 'Mark', 'Assaf', 'M', datetime.date(1986, 1, 28)),
 (462611, datetime.date(1960, 2, 21), 'Mark', 'Kobara', 'M', datetime.date(1987, 9, 4)),
 (462813, datetime.date(1957, 1, 10), 'Mark', 'Pillow', 'F', datetime.date(1986, 7, 11)),
 (463452, datetime.date(1953, 12, 29), 'Mark', 'Gajiwala', 'F', datetime.date(1996, 4, 16)),
 (464485, datetime.date(1954, 8, 27), 'Mark', 'Hebert', 'F', datetime.date(1991, 3, 23)),
 (464722, datetime.date(1959, 8, 30), 'Mark', 'Eastman', 'M', datetime.date(1989, 6, 29)),
 (465868, datetime.date(1952, 9, 3), 'Mark', 'Terwilliger', 'F', datetime.date(1990, 10, 27)),
 (466305, datetime.date(1957, 8, 3), 'Mark', 'Decleir', 'M', datetime.date(1990, 12, 12)),
 (467333, datetime.date(1952, 12, 16), 'Mark', 'Hanabata', 'M', datetime.date(1987, 10, 30)),
 (468155, datetime.date(1964, 5, 14), 'Mark', 'Prochazka', 'F', datetime.date(1995, 4, 23)),
 (468191, datetime.date(1959, 11, 14), 'Mark', 'Lubachevsky', 'M', datetime.date(1988, 12, 18)),
 (469376, datetime.date(1960, 5, 2), 'Mark', 'Garigliano', 'M', datetime.date(1987, 10, 29)),
 (470212, datetime.date(1954, 11, 21), 'Mark', 'Fraisse', 'F', datetime.date(1985, 6, 13)),
 (471786, datetime.date(1959, 3, 27), 'Mark', 'Ashish', 'M', datetime.date(1989, 6, 24)),
 (475660, datetime.date(1959, 11, 2), 'Mark', 'Selvestrel', 'F', datetime.date(1985, 11, 8)),
 (478696, datetime.date(1956, 12, 12), 'Mark', 'Hennebert', 'F', datetime.date(1988, 3, 25)),
 (479606, datetime.date(1952, 9, 26), 'Mark', 'Trachtenberg', 'F', datetime.date(1990, 9, 18)),
 (480258, datetime.date(1962, 4, 2), 'Mark', 'Fujisaki', 'M', datetime.date(1993, 12, 20)),
 (484024, datetime.date(1962, 7, 3), 'Mark', 'Langford', 'M', datetime.date(1987, 6, 19)),
 (484554, datetime.date(1960, 10, 28), 'Mark', 'Chinen', 'F', datetime.date(1989, 1, 20)),
 (484595, datetime.date(1961, 6, 10), 'Mark', 'Auria', 'M', datetime.date(1986, 5, 8)),
 (484860, datetime.date(1963, 1, 25), 'Mark', 'Kakkar', 'M', datetime.date(1987, 1, 2)),

***

## step 7: Saving query results to a file

We have a query that returns a subset of the employees table,  
but how can you get this onto your computer in a form that  
Excel will understand?

You could use your mouse to copy the results displayed on this page,  
open Excel and then paste the results into a spreadsheet. That approach  
works well enough for small data sets, but what about really large data?

The best way to handle big datasets is to save the results to a file,  
and then download that file to your PC.

The first step is to run the query again, and tell sql to put the results  
in a variable.

For instance, if we wanted to put the query results from above into a variable  
named "resultset1" can can issue this command:
```mySQL
resultset1 = %sql select * from employees where first_name = 'Mark'
```

In [12]:
resultset1 = %sql select * from employees where first_name = 'Mark'

230 rows affected.

Instead of displaying all the rows that were returned by the query, the notebook simply  
displayed the number of rows returned. This is very convenient for handling large amounts of data.

Now that we have a variable with the data, we can use a little python code to reformat  
the results into CSV (Comma Separated Value) format, which is something Excel understands.

We can do this by importing the csv package (which knows how to write CSV formatted files).
```python
import csv
```

we then open a file named 'resultset1.csv', and make a filewriter that reads each row in  
the viable that holds the results and writes it out in CSV format to the file
```python
with open('resultset1.csv', 'w', newline='') as csvfile:
    filewriter = csv.writer(csvfile, dialect='excel')
    for row in resultset1:
        filewriter.writerow(row)
```

We can combine these two steps to create a CSV formatted output file:

In [13]:
import csv
with open('resultset1.csv', 'w', newline='') as csvfile:
    filewriter = csv.writer(csvfile, dialect='excel')
    for row in resultset1:
        filewriter.writerow(row)

***
To verify that the output file exists, let's ask the notebook to display the current directory using the command
```bash
ls -l
```

The directory listing from the 'ls' command should include a file named
```
resultset1.csv
```

In [14]:
ls -l

total 248
-rw-r--r-- 1 jovyan  1000 237091 Sep 28 18:22 mysql-example.ipynb
-rw-rw-r-- 1 jovyan  1000   1218 Sep 28 18:15 restore-my-notebook.ipynb
-rw-rw-r-- 1 jovyan users  10307 Sep 28 18:23 resultset1.csv

***
## step 8: Download the results file

At the top of this page, underneath the 'Jupyter' name and icon, there are several options  
(File, Edit, View, Insert, etc...). You can download any file that you are viewing by  
selecting the download option under the File menu (once you are viewing the file).

In other words, to download the CSV results file we just created, we need to open it,  
then select the download option from the File menu in the window with the results after  
we open them.

There are several ways to open the resultset1.csv file. You can
- [click this link](/edit/resultset1.csv "open resultset1.csv") to open resultset1.csv
- select resultset1.csv from the "Open" option under the File menu
- click on the Jupyter icon at the top of this page to get a list of files, then select the resultset1.csv file

***
# Advanced topics

## How many different first names are there?

The clause 'distinct' tells SQL to return a collection of unique values rather than
every value.  
This is useful if you want to find out how many different first names 
there are in the employees table.

The command 
```SQL
select distinct first_name from employees;
```
will give us a list of the unique first names, but the list is not necessarily in any particular order.  
We can add an optional 'order by' clause to that command to tell SQL how to order the results. 

For example, if we want to order the results in reverse alphabetical order, the clause
```SQL
order by first_name desc
```
tells mySQL which column to order by and to order in descending (desc) order.

Putting this all together we get a command to get unique names in reverse alphbetical order:
```SQL
select distinct first_name from employees order by first_name desc;
```

In [15]:
%sql select distinct first_name from employees order by first_name desc;

1275 rows affected.

[('Zvonko',),
 ('Zsolt',),
 ('Zorica',),
 ('Zongyan',),
 ('Ziyad',),
 ('Ziya',),
 ('Ziva',),
 ('Zito',),
 ('Zita',),
 ('Zissis',),
 ('Zine',),
 ('Zijian',),
 ('Zhongwei',),
 ('Zhonghui',),
 ('Zhonghua',),
 ('Zhiwei',),
 ('Zhilian',),
 ('Zhiguo',),
 ('Zhigen',),
 ('Zhensheng',),
 ('Zhenhua',),
 ('Zhenbing',),
 ('Zhaofang',),
 ('Zhanqiu',),
 ('Zeydy',),
 ('Zengping',),
 ('Zeljko',),
 ('Zejun',),
 ('Zdislav',),
 ('Yuuichi',),
 ('Yuriy',),
 ('Yurij',),
 ('Yurii',),
 ('Yuqun',),
 ('Yuping',),
 ('Yunming',),
 ('Yuichiro',),
 ('Yuguang',),
 ('Yuchang',),
 ('Yucel',),
 ('Yucai',),
 ('Youssef',),
 ('Youpyo',),
 ('Younwoo',),
 ('Youngkon',),
 ('Youjian',),
 ('Yoshinari',),
 ('Yoshimitsu',),
 ('Yongqiao',),
 ('Yongmin',),
 ('Yongmao',),
 ('Yonghong',),
 ('Yonghoan',),
 ('Yongdong',),
 ('Yolla',),
 ('Ymte',),
 ('Yishay',),
 ('Yishai',),
 ('Yinlin',),
 ('Yinghua',),
 ('Yifei',),
 ('Yefim',),
 ('Yechiam',),
 ('Yechezkel',),
 ('Yannis',),
 ('Yannik',),
 ('Yakkov',),
 ('Yakichi',),
 ('Yahiko',),
 ('Yagil',),
 ('Yaghout',),
 ('Xumin',),
 ('Xuejun',),
 ('Xuejia',),
 ('Xuedong',),
 ('Xudong',),
 ('Xiping',),
 ('Xiong',),
 ('Xinyu',),
 ('Xinglin',),
 ('Xinan',),
 ('Xiaoshan',),
 ('Xiaoqiu',),
 ('Xiaoqiang',),
 ('Xiaopeng',),
 ('Xiaoheng',),
 ('Xiaocheng',),
 ('Xiaobin',),
 ('Xianlong',),
 ('Xiahua',),
 ('Xiadong',),
 ('Wuxu',),
 ('Woody',),
 ('Wonhee',),
 ('Wojceich',),
 ('Wilmer',),
 ('Willard',),
 ('Werner',),
 ('Weiyi',),
 ('Weiye',),
 ('Weiwu',),
 ('Weiru',),
 ('Weijing',),
 ('Weidon',),
 ('Weicheng',),
 ('Wayne',),
 ('Wanqing',),
 ('Waiman',),
 ('Vugranam',),
 ('Volkmar',),
 ('Vojin',),
 ('Vivian',),
 ('Vitaly',),
 ('Vitali',),
 ('Visit',),
 ('Vishwani',),
 ('Vishv',),
 ('Vishu',),
 ('Vincent',),
 ('Vidya',),
 ('Vidar',),
 ('Vesna',),
 ('Venkatesan',),
 ('Vatsa',),
 ('Vasiliy',),
 ('Vasilis',),
 ('Vasilii',),
 ('Van',),
 ('Valter',),
 ('Valeska',),
 ('Valery',),
 ('Valeri',),
 ('Valdiodio',),
 ('Val',),
 ('Uzi',),
 ('Uwe',),
 ('Utz',),
 ('Utpal',),
 ('Ute',),
 ('Uta',),
 ('Urs',),
 ('Uriel',),
 ('Uri',),
 ('Uno',),
 ('Ung',),
 ('Unal',),
 ('Uma',),
 ('Ult',),
 ('Ulises',),
 ('Uli',),
 ('Ulf',),
 ('Uinam',),
 ('Ugo',),
 ('Udo',),
 ('Udi',),
 ('Udaiprakash',),
 ('Tzvetan',),
 ('Tzu',),
 ('Tze',),
 ('Tuval',),
 ('Turgut',),
 ('Tua',),
 ('Tsz',),
 ('Tsvetan',),
 ('Tsutomu',),
 ('Tsuneo',),
 ('Tse',),
 ('Trygve',),
 ('True',),
 ('Tru',),
 ('Troy',),
 ('Tristan',),
 ('Tremaine',),
 ('Tran',),
 ('Toshimori',),
 ('Toshimo',),
 ('Toshimitsu',),
 ('Toshimi',),
 ('Toshiko',),
 ('Toshiki',),
 ('Torsten',),
 ('Tooru',),
 ('Toong',),
 ('Tonny',),
 ('Tonia',),
 ('Toney',),
 ('Tomoyuki',),
 ('Tomokazu',),
 ('Tomofumi',),
 ('Tommaso',),
 ('Tokuyasu',),
 ('Tiina',),
 ('Tianruo',),
 ('Thodoros',),
 ('Theron',),
 ('Theirry',),
 ('Thanasis',),
 ('Teunis',),
 ('Tetsushi',),
 ('Tetsurou',),
 ('Tesuya',),
 ('Tesuro',),
 ('Teruyuki',),
 ('Terresa',),
 ('Temple',),
 ('Teiji',),
 ('Tayeb',),
 ('Tamiya',),
 ('Takushi',),
 ('Takanari',),
 ('Takahito',),
 ('Takahiro',),
 ('Takahira',),
 ('Taizo',),
 ('Taisook',),
 ('Taiji',),
 ('Taegyun',),
 ('Tadanori',),
 ('Tadahiro',),
 ('Tadahiko',),
 ('Szabolcs',),
 ('Syozo',),
 ('Sverrir',),
 ('Sven',),
 ('Suzette',),
 ('Suvo',),
 ('Susumu',),
 ('Susuma',),
 ('Sushant',),
 ('Susanta',),
 ('Susanne',),
 ('Susanna',),
 ('Surveyors',),
 ('Supot',),
 ('Sungwon',),
 ('Sumant',),
 ('Sumali',),
 ('Sukumar',),
 ('Sugwoo',),
 ('Suebskul',),
 ('Sudharsan',),
 ('Sudhanshu',),
 ('Subir',),
 ('Subhrajyoti',),
 ('Subhash',),
 ('Subhankar',),
 ('Subhada',),
 ('Subbu',),
 ('Stevo',),
 ('Steve',),
 ('Stepehn',),
 ('Stella',),
 ('Stein',),
 ('Steen',),
 ('Stamatina',),
 ('Stafford',),
 ('Stabislas',),
 ('Srinidhi',),
 ('Sreenivas',),
 ('Sreekrishna',),
 ('Spyrose',),
 ('Souichi',),
 ('Sorina',),
 ('Somnath',),
 ('Soenke',),
 ('Snehasis',),
 ('Slavian',),
 ('Sivanarayana',),
 ('Sigeru',),
 ('Siddarth',),
 ('Sibyl',),
 ('Siamak',),
 ('Shuzo',),
 ('Shushma',),
 ('Shunichi',),
 ('Shuky',),
 ('Shuji',),
 ('Shuichi',),
 ('Shuho',),
 ('Shugo',),
 ('Shrikanth',),
 ('Shridhar',),
 ('Shounak',),
 ('Shooichi',),
 ('Shmuel',),
 ('Shiv',),
 ('Shirish',),
 ('Shir',),
 ('Shin',),
 ('Shimshon',),
 ('Shim',),
 ('Shih',),
 ('Shigeu',),
 ('Shigeo',),
 ('Shigenori',),
 ('Shigeichiro',),
 ('Shigehito',),
 ('Shigehiro',),
 ('Shigeaki',),
 ('Shietung',),
 ('Shichao',),
 ('Shen',),
 ('Shem',),
 ('Shaz',),
 ('Shay',),
 ('Shawna',),
 ('Shaw',),
 ('Shaunak',),
 ('Shaowen',),
 ('Shaowei',),
 ('Shao',),
 ('Shan',),
 ('Sham',),
 ('Shalesh',),
 ('Shaleah',),
 ('Shakhar',),
 ('Shaibal',),
 ('Shai',),
 ('Shahid',),
 ('Shahar',),
 ('Shahaf',),
 ('Shahab',),
 ('Seshu',),
 ('Serif',),
 ('Sergi',),
 ('Serge',),
 ('Serenella',),
 ('Serap',),
 ('Seongbin',),
 ('Seongbae',),
 ('Selwyn',),
 ('Sedat',),
 ('Satyanarayana',),
 ('Satosi',),
 ('Satoru',),
 ('Sastry',),
 ('Sashi',),
 ('Sasan',),
 ('Sarita',),
 ('Sariel',),
 ('Sanjoy',),
 ('Sanjiv',),
 ('Sanjit',),
 ('Sanjeeva',),
 ('Sanjay',),
 ('Sanjai',),
 ('Saniya',),
 ('Sangeeta',),
 ('Sandeepan',),
 ('Samphel',),
 ('Sampalli',),
 ('Salvador',),
 ('Sakthirel',),
 ('Sajjan',),
 ('Sajjad',),
 ('Sailaja',),
 ('Sahrah',),
 ('Saeko',),
 ('Saeed',),
 ('Sadun',),
 ('Sadok',),
 ('Sadegh',),
 ('Saddek',),
 ('Sachio',),
 ('Sachin',),
 ('Sachem',),
 ('Sachar',),
 ('Rutger',),
 ('Rosli',),
 ('Rosita',),
 ('Rosine',),
 ('Roselyn',),
 ('Rosella',),
 ('Rosalyn',),
 ('Rosalie',),
 ('Ronnie',),
 ('Ronghao',),
 ('Roded',),
 ('Roddy',),
 ('Rimon',),
 ('Rimli',),
 ('Rildo',),
 ('Richard',),
 ('Richara',),
 ('Reuven',),
 ('Renny',),
 ('Renee',),
 ('Remzi',),
 ('Remmert',),
 ('Remko',),
 ('Remco',),
 ('Reinhold',),
 ('Reinhard',),
 ('Rayond',),
 ('Ravishankar',),
 ('Rasikan',),
 ('Rasiah',),
 ('Ranga',),
 ('Randy',),
 ('Randi',),
 ('Rance',),
 ('Ranan',),
 ('Ramzi',),
 ('Ramya',),
 ('Ramalingam',),
 ('Ramachenga',),
 ('Rajmohan',),
 ('Raimond',),
 ('Rafols',),
 ('Rafail',),
 ('Rafael',),
 ('Radoslaw',),
 ('Radhika',),
 ('Radhia',),
 ('Radhakrishnan',),
 ('Qunsheng',),
 ('Quingbo',),
 ('Qiwen',),
 ('Qingxiang',),
 ('Przemyslawa',),
 ('Prodip',),
 ('Premsyl',),
 ('Premal',),
 ('Prasadram',),
 ('Pranjal',),
 ('Pranay',),
 ('Pranav',),
 ('Pranas',),
 ('Pramod',),
 ('Pragnesh',),
 ('Pradeep',),
 ('Poornachandra',),
 ('Poorav',),
 ('Pohua',),
 ('Piyush',),
 ('Piyawadee',),
 ('Pintsang',),
 ('Phuoc',),
 ('Phule',),
 ('Phillip',),
 ('Petter',),
 ('Peternela',),
 ('Persi',),
 ('Perry',),
 ('Perla',),
 ('Percy',),
 ('Peer',),
 ('Patricio',),
 ('Patricia',),
 ('Pasqua',),
 ('Pascal',),
 ('Parviz',),
 ('Parto',),
 ('Parke',),
 ('Paris',),
 ('Paraskevi',),
 ('Pantung',),
 ('Panayotis',),
 ('Paloma',),
 ('Palash',),
 ('Padma',),
 ('Paddy',),
 ('Owen',),
 ('Ottavia',),
 ('Otmar',),
 ('Otilia',),
 ('Oscar',),
 ('Oscal',),
 ('Ortrun',),
 ('Ortrud',),
 ('Olivera',),
 ('Oldrich',),
 ('Oksana',),
 ('Ohad',),
 ('Oguz',),
 ('Odysseas',),
 ('Odoardo',),
 ('Odinaldo',),
 ('Oddvar',),
 ('Noritoshi',),
 ('Nobuyoshi',),
 ('Nitsan',),
 ('Niteen',),
 ('Nishit',),
 ('Nirmal',),
 ('Niranjan',),
 ('Nimmagadda',),
 ('Nikolaus',),
 ('Nikolaos',),
 ('Nigel',),
 ('Nidapan',),
 ('Niclas',),
 ('Nevio',),
 ('Nevin',),
 ('Neven',),
 ('Neelam',),
 ('Nectarios',),
 ('Nechama',),
 ('Navin',),
 ('Navid',),
 ('Nathan',),
 ('Nathalie',),
 ('Narain',),
 ('Naraig',),
 ('Nalini',),
 ('Nakhoon',),
 ('Nahum',),
 ('Nahla',),
 ('Nahid',),
 ('Nagui',),
 ('Naftaly',),
 ('Naftali',),
 ('Nadjib',),
 ('Muzhong',),
 ('Murthy',),
 ('Munir',),
 ('Muneo',),
 ('Munenori',),
 ('Munehiro',),
 ('Munehiko',),
 ('Mrinalini',),
 ('Mountaz',),
 ('Moty',),
 ('Mototsugu',),
 ('Moto',),
 ('Moti',),
 ('Mostafa',),
 ('Moss',),
 ('Morris',),
 ('Morrie',),
 ('Moriyoshi',),
 ('Mori',),
 ('Moon',),
 ('Mooi',),
 ('Monique',),
 ('Moni',),
 ('Mong',),
 ('Mona',),
 ('Mokhtar',),
 ('Moie',),
 ('Mohua',),
 ('Mohit',),
 ('Moheb',),
 ('Mohd',),
 ('Mohan',),
 ('Mohammed',),
 ('Mohammad',),
 ('Mohamadou',),
 ('Mizuhito',),
 ('Miyeon',),
 ('Mitsuyuki',),
 ('Mitchel',),
 ('Mircea',),
 ('Miquel',),
 ('Miomir',),
 ('Mingzeng',),
 ('Mingsen',),
 ('Minghong',),
 ('Mingdong',),
 ('Mikhail',),
 ('Mihalis',),
 ('Michaela',),
 ('Menkae',),
 ('Mechthild',),
 ('Mayuri',),
 ('Mayumi',),
 ('Mayuko',),
 ('Maya',),
 ('Matt',),
 ('Mats',),
 ('Matk',),
 ('Masoud',),
 ('Masato',),
 ('Masasuke',),
 ('Masaru',),
 ('Masanao',),
 ('Masamitsu',),
 ('Masami',),
 ('Masali',),
 ('Masako',),
 ('Masaki',),
 ('Masadi',),
 ('Mary',),
 ('Martins',),
 ('Martine',),
 ('Martina',),
 ('Martijn',),
 ('Martien',),
 ('Martial',),
 ('Mart',),
 ('Marsja',),
 ('Marsha',),
 ('Marsal',),
 ('Marlo',),
 ('Marla',),
 ('Marl',),
 ('Marko',),
 ('Marke',),
 ('Mark',),
 ('Marjo',),
 ('Mariusz',),
 ('Marit',),
 ('Maris',),
 ('Mario',),
 ('Marin',),
 ('Marie',),
 ('Mariangiola',),
 ('Maria',),
 ('Mari',),
 ('Margo',),
 ('Margareta',),
 ('Maren',),
 ('Marek',),
 ('Marco',),
 ('Marc',),
 ('Mara',),
 ('Manu',),
 ('Manton',),
 ('Mantis',),
 ('Mansur',),
 ('Manohar',),
 ('Manibrata',),
 ('Mani',),
 ('Mang',),
 ('Mandell',),
 ('Mana',),
 ('Mamdouh',),
 ('Malu',),
 ('Make',),
 ('Makato',),
 ('Maja',),
 ('Maik',),
 ('Maia',),
 ('Mahmut',),
 ('Mahendra',),
 ('Maha',),
 ('Magy',),
 ('Magdalena',),
 ('Mads',),
 ('Mack',),
 ('Macha',),
 ('Mabry',),
 ('Mabo',),
 ('Mabhin',),
 ('Lunjin',),
 ('Luise',),
 ('Luisa',),
 ('Luigi',),
 ('Luerbio',),
 ('Lucien',),
 ('Lucian',),
 ('Lubomir',),
 ('Lorien',),
 ('Lokesh',),
 ('Lobel',),
 ('Limsoon',),
 ('LiMin',),
 ('Lillian',),
 ('Lijie',),
 ('Lijia',),
 ('Lihong',),
 ('Lidong',),
 ('Licheng',),
 ('Leucio',),
 ('Leszek',),
 ('Leon',),
 ('Lenore',),
 ('Leni',),
 ('Lene',),
 ('Lena',),
 ('Lein',),
 ('Leif',),
 ('Leen',),
 ('Lech',),
 ('Leandro',),
 ('Leah',),
 ('Leaf',),
 ('Laurentiu',),
 ('Larisa',),
 ('Lansing',),
 ('Lalit',),
 ('Lakshmi',),
 ('Kyoichi',),
 ('Kwun',),
 ('Kwok',),
 ('Kwee',),
 ('Kwangyoen',),
 ('Kwangsub',),
 ('Kwangjo',),
 ('Kwangho',),
 ('Kwan',),
 ('Kshitij',),
 ('Kristof',),
 ('Kristinn',),
 ('Kristine',),
 ('Kristina',),
 ('Kristin',),
 ('Kristian',),
 ('Krister',),
 ('Kristen',),
 ('Krisda',),
 ('Krassimir',),
 ('Kousuke',),
 ('Kotesh',),
 ('Koldo',),
 ('Kolar',),
 ('Kokou',),
 ('Koichi',),
 ('Kiyotoshi',),
 ('Kiyomitsu',),
 ('Kiyokazu',),
 ('Kitty',),
 ('Kish',),
 ('Kirk',),
 ('Kinh',),
 ('King',),
 ('Kien',),
 ('Kiam',),
 ('Khun',),
 ('Khue',),
 ('Khosrow',),
 ('Khoa',),
 ('Khedija',),
 ('Khatoun',),
 ('Khalil',),
 ('Khalid',),
 ('Khaled',),
 ('Keung',),
 ('Kersti',),
 ('Kerryn',),
 ('Kerhong',),
 ('Kenton',),
 ('Kensyu',),
 ('Kensei',),
 ('Kenroku',),
 ('Kendra',),
 ('Kellyn',),
 ('Kellie',),
 ('Keiichiro',),
 ('Kazuyasu',),
 ('Kazunori',),
 ('Kazuhito',),
 ('Kazuhisa',),
 ('Kazuhiro',),
 ('Kazuhira',),
 ('Kazuhiko',),
 ('Kazuhide',),
 ('Kayoko',),
 ('KayLiang',),
 ('Kauko',),
 ('Katsuyuki',),
 ('Katsuo',),
 ('Kasturi',),
 ('Kasidit',),
 ('Karsten',),
 ('Karoline',),
 ('Karlis',),
 ('Kannan',),
 ('Kankanahalli',),
 ('Kamran',),
 ('Kamakshi',),
 ('Kaijung',),
 ('Kagan',),
 ('Juyoung',),
 ('Junsik',),
 ('Junichi',),
 ('Jungsoon',),
 ('Juichirou',),
 ('Joydip',),
 ('Jovan',),
 ('Jouni',),
 ('Jouko',),
 ('Josyula',),
 ('Jordanka',),
 ('Jongsuk',),
 ('Jolita',),
 ('JoAnne',),
 ('JoAnna',),
 ('JiYoung',),
 ('Jixiang',),
 ('Jiong',),
 ('Jinya',),
 ('Jinxi',),
 ('Jinpo',),
 ('Jingling',),
 ('Jianwen',),
 ('Jiann',),
 ('Jianhui',),
 ('Jianhua',),
 ('Jianhao',),
 ('Jiang',),
 ('Jiakeng',),
 ('Jiafu',),
 ('Jessie',),
 ('Jeong',),
 ('Jenwei',),
 ('Jeanne',),
 ('Jeanna',),
 ('Jeane',),
 ('Jayson',),
 ('Jayesh',),
 ('Jasminko',),
 ('Jaroslava',),
 ('Jaques',),
 ('Janche',),
 ('Janalee',),
 ('Jamaludin',),
 ('Jaihie',),
 ('Jaideep',),
 ('Jahangir',),
 ('Jagoda',),
 ('Jaewoo',),
 ('Jaewon',),
 ('Jacqueline',),
 ('Jacopo',),
 ('Jackson',),
 ('Jaber',),
 ('Jaana',),
 ('Izaskun',),
 ('Itzchak',),
 ('Ishfaq',),
 ('Isamu',),
 ('Isaac',),
 ('Irene',),
 ('Irena',),
 ('Ipke',),
 ('Ioana',),
 ('Insup',),
 ('Ingmar',),
 ('Ingemar',),
 ('Indrajit',),
 ('Inderjeet',),
 ('IEEE',),
 ('Idoia',),
 ('Ibibia',),
 ('Iara',),
 ('Hyuncheol',),
 ('Hyuckchul',),
 ('Huiqun',),
 ('Huican',),
 ('Hugo',),
 ('Hugh',),
 ('Huei',),
 ('Huan',),
 ('Huai',),
 ('Hsiangchu',),
 ('Howell',),
 ('Houman',),
 ('Horward',),
 ('Hongzue',),
 ('Hongzhu',),
 ('Honglan',),
 ('Honesty',),
 ('Holgard',),
 ('Hitomi',),
 ('Hitofumi',),
 ('Hisao',),
 ('Hiroyasu',),
 ('Hironoby',),
 ('Hironobu',),
 ('Hirochika',),
 ('Hinrich',),
 ('Hilary',),
 ('Hilari',),
 ('Hideyuki',),
 ('Hideo',),
 ('Hidekazu',),
 ('Hidefumi',),
 ('Hidde',),
 ('Hercules',),
 ('Herbert',),
 ('Herb',),
 ('Heping',),
 ('Heon',),
 ('Henk',),
 ('Heng',),
 ('Hein',),
 ('Heekeun',),
 ('Heeju',),
 ('Heejo',),
 ('Heather',),
 ('Hausi',),
 ('Hauke',),
 ('Hatsukazu',),
 ('Hatim',),
 ('Hatem',),
 ('Harngdar',),
 ('Harjit',),
 ('Halsur',),
 ('Haldun',),
 ('Haldon',),
 ('Hairong',),
 ('Hailing',),
 ('Guttorm',),
 ('Guther',),
 ('Gurbir',),
 ('Guozhong',),
 ('Guoxiang',),
 ('Gunilla',),
 ('Gully',),
 ('Guiseppe',),
 ('Guenter',),
 ('Gudjon',),
 ('Guangming',),
 ('Guadalupe',),
 ('Gro',),
 ('Gritta',),
 ('Gretta',),
 ('Gregory',),
 ('Greger',),
 ('Gou',),
 ('Gor',),
 ('Gopalakrishnan',),
 ('Goo',),
 ('Gonzalo',),
 ('Goncalo',),
 ('Golgen',),
 ('Goh',),
 ('Goetz',),
 ('Godehard',),
 ('Goa',),
 ('Gladys',),
 ('Gita',),
 ('Girolamo',),
 ('Giri',),
 ('Giordano',),
 ('Gio',),
 ('Gino',),
 ('Gina',),
 ('Gill',),
 ('Gilbert',),
 ('Gila',),
 ('Gil',),
 ('Gift',),
 ('Giap',),
 ('Giao',),
 ('Gianluca',),
 ('Gian',),
 ('Ghassan',),
 ('Gererd',),
 ('Geraldo',),
 ('Ger',),
 ('Georgy',),
 ('Georgi',),
 ('George',),
 ('Georg',),
 ('Geoffry',),
 ('Geoffrey',),
 ('Geoff',),
 ('Genta',),
 ('Gennady',),
 ('Gennadi',),
 ('Genki',),
 ('Genevieve',),
 ('Gen',),
 ('Gay',),
 ('Gaurav',),
 ('Garnik',),
 ('Garnet',),
 ('Gao',),
 ('Gal',),
 ('Gaetan',),
 ('Gadiel',),
 ('Gad',),
 ('Fusako',),
 ('Fuqing',),
 ('Fun',),
 ('Fumiyo',),
 ('Fumiya',),
 ('Fumitake',),
 ('Fumitaka',),
 ('Fumino',),
 ('Fumiko',),
 ('Froduald',),
 ('Freyja',),
 ('Frederique',),
 ('Frazer',),
 ('Franziska',),
 ('Francoise',),
 ('Francesca',),
 ('Fox',),
 ('Foong',),
 ('Florina',),
 ('Florian',),
 ('Flemming',),
 ('Filipp',),
 ('Filipe',),
 ('Ferdinand',),
 ('Fen',),
 ('Felicidad',),
 ('Feiyu',),
 ('Feixiong',),
 ('Feipei',),
 ('Fei',),
 ('Fayez',),
 ('Fay',),
 ('Fatemeh',),
 ('Fan',),
 ('Falguni',),
 ('Faiza',),
 ...]

***
## Test your understanding

Now that you have worked through the tutorial it is time to see well do you understand the material.  
Can you answer the questions below by creating your own SQL queries?
***

### 1.) How many different last names are there in the employees table?

***
### 2.) How many different salaries are there?